=== ddsimoes/sbql4j/SBQL4J/sbql_test/books.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="catalogue" type="catalogueType" />

	<xs:complexType name="catalogueType">
		<xs:sequence>
			<xs:element name="book" minOccurs="0" maxOccurs="unbounded"
				type="bookType" />
			<xs:element name="publisher" minOccurs="0" maxOccurs="unbounded"
				type="publisherType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="title" minOccurs="1" maxOccurs="1"
				type="xs:string" />
			<xs:element name="publisher" minOccurs="1" maxOccurs="1"
				type="xs:string" />
			<xs:element name="price" minOccurs="1" maxOccurs="2">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:decimal">
							<xs:attribute name="kind">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="retail" />
										<xs:enumeration value="wholesale" />
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ISBN" minOccurs="1" maxOccurs="1"
				type="xs:string" />
		</xs:sequence>
		<xs:attribute name="rok" type="xs:integer" use="optional" />
		<xs:attribute name="year" type="xs:integer" use="optional" />
	</xs:complexType>

	<xs:complexType name="publisherType">
		<xs:sequence>
			<xs:element name="abbreviation" minOccurs="1" maxOccurs="1"
				type="xs:string" />
			<xs:element name="name" minOccurs="1" maxOccurs="3"
				type="xs:string" />
			<xs:element name="country" minOccurs="1" maxOccurs="2"
				type="xs:string" />
		</xs:sequence>
	</xs:complexType>


</xs:schema>

=== ddsimoes/sbql4j/SBQL4J/sbql_test/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--   <!DOCTYPE catalogue SYSTEM "books.dtd"> -->
<catalogue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="books.xsd">
	<book rok="1994">
		<title>TCP/IP Illustrated</title>
		<publisher>AW</publisher>
		<price>65.95</price>
		<ISBN>ISBN-0201633469</ISBN>
	</book>

	<book year="1992">
		<title>Advanced Programming in the Unix environment</title>
		<publisher>AW</publisher>
		<price kind="retail">65.95</price>
		<price kind="wholesale">50.00</price>
		<ISBN>ISBN-020163346X</ISBN>
	</book>

	<book year="2000">
		<title>Data on the Web</title>
		<publisher>MK</publisher>
		<price kind="retail">39.95</price>
		<ISBN>ISBN-3343163346</ISBN>
	</book>

	<book year="1999">
		<title>The Economics of Technology and Content for Digital TV</title>
		<publisher>KA</publisher>
		<price kind="retail">129.95</price>
		<ISBN>ISBN-433348634X</ISBN>
	</book>


	<publisher>
		<abbreviation>AW</abbreviation>
		<name>Addison-Wesley</name>
		<country>USA</country>
	</publisher>

	<publisher>
		<abbreviation>KA</abbreviation>
		<name>Kluwer Academic Publishers</name>
		<country>Holandia</country>
	</publisher>

	<publisher>
		<abbreviation>MK</abbreviation>
		<name>Morgan Kaufmann Publishers</name>
		<country>USA</country>
	</publisher>



</catalogue>
